linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity:  15
  dupl:
    threshold: 100
  goconst:
    min-len:  2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length:  120
  goimports:
    local-prefixes: github.com/misteregis/go-example-project
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\. go
      linters:
        - gomnd
        - gocyclo
        - errcheck
        - dupl
        - gosec

run:
  timeout: 5m
  tests: true
